### ISSUE TITLE
Compilation errors for POD synopsis

### ISSUE THREAD

**Issue by jonasbn** [jack-karamanian/vscode-perlsyntax#5]
I have observed a compilation issues raised for a SYNOPSIS / POD (documentation) section.

> "use" not allowed in expression at - line 7, at end of line

A good example: [PPIx::Regexp::Dumper](https://metacpan.org/pod/PPIx::Regexp::Dumper), check the [SYNOPSIS section](https://metacpan.org/source/WYANT/PPIx-Regexp-0.061/lib/PPIx/Regexp/Dumper.pm#L7) line 7 (see also below, the use statement in the synopsis.

```perl
=head1 NAME

PPIx::Regexp::Dumper - Dump the results of parsing regular expressions

=head1 SYNOPSIS
 
use PPIx::Regexp::Dumper;
PPIx::Regexp::Dumper->new( 'qr{foo}smx' )
    ->print();
```

**Comment by jack-karamanian** [comment]
[This commit](https://github.com/jack-karamanian/perl-syntax/commit/9e0324ff975600bf6f22a6902a3f02d2449a0dab) should fix this. A new release should be out shortly.

**Comment by jonasbn** [comment]
Thanks a bunch, that was quick - I will check it out

Marvellous plugin BTW - thanks for creating and sharing 👍

**Comment by jonasbn** [comment]
I have updated this morning and it seems to work :-)
